# Generated by Django 4.0.3 on 2022-05-18 03:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clube',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
                ('qualidade', models.IntegerField(default=50)),
                ('jogosDisputados', models.IntegerField(default=0, editable=False)),
                ('vitorias', models.IntegerField(default=0, editable=False)),
                ('empates', models.IntegerField(default=0, editable=False)),
                ('derrotas', models.IntegerField(default=0, editable=False)),
                ('golosMarcados', models.IntegerField(default=0, editable=False)),
                ('golosSofridos', models.IntegerField(default=0, editable=False)),
                ('diferencaDeGolos', models.IntegerField(default=0, editable=False)),
                ('pontos', models.IntegerField(default=0, editable=False)),
                ('nacionalidade', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Liga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(default='liga', max_length=30)),
                ('listaEquipas', models.ManyToManyField(to='leagueTables.clube')),
            ],
        ),
        migrations.CreateModel(
            name='Jornada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('liga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liga', to='leagueTables.liga')),
            ],
        ),
        migrations.CreateModel(
            name='Jogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('golosCasa', models.IntegerField(default=0, editable=False)),
                ('golosFora', models.IntegerField(default=0, editable=False)),
                ('concluido', models.BooleanField(default=False, editable=False)),
                ('equipaCasa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipaCasa', to='leagueTables.clube')),
                ('equipaFora', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipaFora', to='leagueTables.clube')),
                ('jornada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jornada', to='leagueTables.jornada')),
            ],
        ),
    ]
