# Generated by Django 4.0.3 on 2022-04-30 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leagueTables', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='liga',
            name='nome',
            field=models.CharField(default='liga', max_length=30),
        ),
        migrations.AlterField(
            model_name='clube',
            name='derrotas',
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='clube',
            name='diferencaDeGolos',
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='clube',
            name='empates',
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='clube',
            name='golosMarcados',
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='clube',
            name='golosSofridos',
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='clube',
            name='jogosDisputados',
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='clube',
            name='pontos',
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='clube',
            name='vitorias',
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='jogo',
            name='golosCasa',
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='jogo',
            name='golosFora',
            field=models.IntegerField(default=0, editable=False),
        ),
    ]
