# Generated by Django 4.0.3 on 2022-05-02 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leagueTables', '0003_clube_nacionalidade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clube',
            name='nacionalidade',
            field=models.CharField(max_length=30),
        ),
    ]
