# Generated by Django 4.0.3 on 2022-05-03 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leagueTables', '0004_alter_clube_nacionalidade'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jornada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('listaJogos', models.ManyToManyField(to='leagueTables.jogo')),
            ],
        ),
        migrations.AddField(
            model_name='liga',
            name='jornadas',
            field=models.ManyToManyField(to='leagueTables.jornada'),
        ),
    ]
